### ISSUE TITLE
The sum of Infinity and -Infinity causes NaN

### ISSUE THREAD

**Issue by Triuman** [DerSchmale/tympanum#3]
In the [`dot`](https://github.com/DerSchmale/tympanum/blob/1b8c455b2f6d4528f58feeb783a96276b17a23ab/src/math/VecMath.ts#L31C28-L31C28) function, it sums up the multiplication of two numbers. But if the two resulting numbers are Infinity and -Infinity, it results in `NaN` value for `d` variable.

Then, it causes [`hyperplaneFromPoints`](https://github.com/DerSchmale/tympanum/blob/1b8c455b2f6d4528f58feeb783a96276b17a23ab/src/math/VecMath.ts#L208) function to return a vector with `NaN` values. Then, in the [`getOptimalStart`](https://github.com/DerSchmale/tympanum/blob/main/src/hull/QuickHull.ts#L162) function, it pushes `undefined` via `planePts.push(points[p]);` since the `p` still equals to `-1`.

Finally, it causes an error: `tympanum.module.js:161 Uncaught TypeError: Cannot read properties of undefined (reading '0')`

```Javascript
        for (var j = 0; j < dim; ++j)
            v[j] = v0[j] - pt[j];
```

This is a part of the code in Miniverse.

```Typescript
function rebuildDelaunay() {
  probePositions = [];

  // Assure some size vertically
  const min = vec3.fromValues(Infinity, -30, Infinity);
  const max = vec3.fromValues(-Infinity, 30, -Infinity);

  irradianceProbes.forEach((probe, i) => {
    vec3.min(min, min, probe.position);
    vec3.max(max, max, probe.position);
    probePositions[i] = probe.position;
  });
  ```

Not sure what the underlying cause because I don't know understand the implementation details. It might be a bug in the software or a misusage. It'd be great @DerSchmale if you could have a look.

**Comment by DerSchmale** [comment]
Hmm is the `irradianceProbes` array empty? If not, the values should no longer be `Infinity` (an Infinity value should not be passed into the delaunay function)

**Comment by Triuman** [comment]
Yeah, the `irradianceProbes` is empty. I'm sorry for bothering with such a simple issue :/ Thank you for the quick fix!

**Comment by DerSchmale** [comment]
No problem, glad to help! :)
